@startuml Arkitektur

!define RECTANGLE class
!define DATABASE database
!define ARROW -[hidden]-> 

RECTANGLE Book {
    +Book b
    +String title
    +String author
    +void addReview(BookReview r)
}

RECTANGLE BookReview {
    +String reviewer
    +int Rating
    +ArrayList<BookReview> reviewsOfBook
    +void addRatingToBook(Book b)
    +void setRating(int rating)
}

RECTANGLE User {
    +User name
    +void writeReview(Book b, int rating)
}

RECTANGLE BookApp {
    +start()
}

DATABASE Books {
    
}

BookApp *-- User: Login
Book *-- "0,n" User: Review book
User *-- "0,n" Book: Reviewed of
Book *-- "1,1" BookReview: Add to
BookReview *-- "0,n" Book: Reviews

@enduml

